import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <body>
              <header
              style={{
                backgroundColor: "blue",
                padding : "20px"
              }}
              >
                  <p>header</p>
              </header>
              {children}
              <footer
              style={{
                backgroundColor: "blue",
                padding : "20px"
              }}
              >
                  <p>footer</p>
              </footer>
          </body>
      </html>
  )
}